### ISSUE TITLE
Browsersync constantly emits errors

### ISSUE THREAD

**Issue by ottok** [Seravo/wp-vagrant#34] opened 2017-03-11 20:41 UTC
The error log is constantly filled with BrowserSync service errors. Viewing the BrowserSync page does not work either.
```
==> /data/log/nginx-error.log <==
2017/03/11 20:38:42 [error] 2899#0: *177 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.25.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:1337/", host: "wordpress.local"

==> /data/log/nginx-error.log <==
2017/03/11 20:40:51 [error] 2899#0: *208 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.25.1, server: browsersync.*, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:1338/favicon.ico", host: "browsersync.wordpress.local", referrer: "https://browsersync.wordpress.local/"
```

**Comment by ottok** [comment] 2017-03-11 20:46
It seems browser-sync cannot run by default, but must be hooked to assets via gulp: https://seravo.com/docs/development/gulp/

**Comment by ottok** [comment] 2017-06-26 11:11
Implement commands wp-browsersync-on and wp-browsersync-off so that browsersync can be disabled. See #39.

**Comment by ottok** [comment] 2017-07-18 11:13
Extra feature:

When `wp-browsersync-on` is run, it could check with `wp option get siteurl` if the site has http or https, and automatically edit the gulpfile and /etc/nginx/sites-enabled/default to run with https so Browsersync can works with https.

**Comment by ottok** [comment] 2017-07-19 10:55
For https support:

**gulpfile.js**
```
    browserSync.init({
        // browsersync with a php server
        proxy: "https://localhost:8080",
        https: {
          key: "/data/wordpress/.vagrant/ssl/development.key",
          cert: "/data/wordpress/.vagrant/ssl/development.crt"
        },
```

**/etc/nginx/sites-enabled/default**
```
upstream: https://wordpress;
```

**Comment by l3ku** [comment] 2017-07-25 08:34
I managed to get browsersync working (UI not working) with https when using:
**gulpfile.js**
```
    browserSync.init({
        // browsersync with a php server
        proxy: "http://localhost:8080",
        https: {
          key: "/data/wordpress/.vagrant/ssl/development.key",
          cert: "/data/wordpress/.vagrant/ssl/development.crt"
        },
```
**/etc/nginx/sites-enabled/default**
```
upstream: https://wordpress;
```

Some notices I made:

- If I add `proxy: "https://localhost:8080"` to /data/wordpress/gulpfile.js, the whole site stops working over browsersync due to 502 error

- When gulp watch is not running, the modification `upstream: https://wordpress;` made to /etc/nginx/sites-available/ causes an 502 error when accessing either https://wordpress.local/ or http://wordpress.local/

**Comment by l3ku** [comment] 2017-08-01 10:14
Development in progress at https://github.com/Seravo/wp-palvelu-vagrant/tree/feature-wp-xdebug-commands. HTTPS support for Browsersync has not yet been implemented into the scripts due to the problems mentioned in the previous comment on this issue.

**Comment by ottok** [comment] 2021-01-27 13:38
This should be fixed and tested in parallel with https://github.com/Seravo/wordpress/issues/140

**Comment by frimro** [comment] 2021-04-29 08:21
Could not replicate Browsersync errors. The UI works fine as well. Closing for now, as the issue is quite old.

**Closed as completed by frimro** 2021-04-29 08:21 UTC
Labels: bug
