### ISSUE TITLE
wp-pull-production-db fails

### ISSUE THREAD

**Issue by apkoponen** [Seravo/wp-vagrant#41] opened 2017-06-13 09:38 UTC
I'm trying to get the box to download the production DB, however this fails with the following error:

```
==> redacted-box: Define new and old siteurl for later search-replacing...
==> redacted-box: /usr/lib/ruby/vendor_ruby/highline.rb:862:in `get_line'
==> redacted-box: : 
==> redacted-box: The input stream is exhausted.
==> redacted-box:  (
==> redacted-box: EOFError
==> redacted-box: )
==> redacted-box: 	from /usr/lib/ruby/vendor_ruby/highline.rb:885:in `get_response'
==> redacted-box: 	from /usr/lib/ruby/vendor_ruby/highline.rb:260:in `ask'
==> redacted-box: 	from /usr/lib/ruby/vendor_ruby/highline.rb:223:in `agree'
==> redacted-box: 	from /usr/local/bin/wp-pull-production-db:48:in `<main>'
==> redacted-box: ==> Production site URL: 
==> redacted-box: ==> Development site URL: http://redacted.local
==> redacted-box: ==> This is a normal WordPress single install.
==> redacted-box: Is the information above correct (yes/no)?
==> redacted-box: Please enter "yes" or "no".
==> redacted-box: Is the information above correct (yes/no)?
==> redacted-box: Remote command execution finished.
The command "wp-pull-production-db" returned a failed exit code. The
error output is shown below:

/usr/lib/ruby/vendor_ruby/highline.rb:862:in `get_line': The input stream is exhausted. (EOFError)
	from /usr/lib/ruby/vendor_ruby/highline.rb:885:in `get_response'
	from /usr/lib/ruby/vendor_ruby/highline.rb:260:in `ask'
	from /usr/lib/ruby/vendor_ruby/highline.rb:223:in `agree'
	from /usr/local/bin/wp-pull-production-db:48:in `<main>'
```

One thing I can see is that the production URL does not get pulled for soem reason. The command for pulling the production URL does however work when issued with the config.yml credentials (`ssh -q redacted@redacted.fi -p 10531 "wp option get siteurl"`)

I'm running Ubuntu 16.04.

**Comment by ottok** [comment] 2017-06-25 19:00
Replied via email that we are unable to reproduce this issue.

**Comment by ottok** [comment] 2017-06-26 05:44
..however another user has been able to reproduce this `get_line` issue at https://github.com/Seravo/wordpress/issues/59. Closing this one as a duplicate.

**Closed as completed** 2017-06-26 10:36 UTC

**Comment by ottok** [comment] 2017-06-29 18:34
@apkoponen @k1sul1 @spktklr Version 20170629.17.0000 of the Seravo WordPress Vagrant box has been released. Enjoy!
