### ISSUE TITLE
Initial wp-pull-production-db fails

### ISSUE THREAD

**Issue by ottok** [Seravo/wp-vagrant#52] opened 2018-06-11 04:48 UTC
It works once Vagrant is fully up and running, but the command initiated by the `vagrant up` wizard does not seem to find the command in the right path:
```
    redacted-box: Pull database from production? (no): yes
==> redacted-box: Executing remote command "wp core install --url=https://redacted.local --title=redacted         --admin_email=vagrant@redacted.local --admin_user=vagrant --admin_password=vagrant"...
==> redacted-box: entering site container... /usr/local/bin/wp core install --url=https://redacted.local --title=redacted --admin_email=vagrant@redacted.local --admin_user=vagrant --admin_password=vagrant
==> redacted-box: |----------------------------------------------------------------------------|
==> redacted-box: | Welcome to Seravo.com!                                                     |
==> redacted-box: | Unauthorized use is forbidden. All connections are monitored and recorded. |
==> redacted-box: |----------------------------------------------------------------------------|
==> redacted-box: Success: WordPress installed successfully.
==> redacted-box: Remote command execution finished.
==> redacted-box: Executing remote command "wp-pull-production-db"...
==> redacted-box: bash: line 5: wp-pull-production-db: command not found
==> redacted-box: Remote command execution finished.
The remote command "wp-pull-production-db" returned a failed exit
code or an exception. The error output is shown below:

bash: line 5: wp-pull-production-db: command not found
```

**Comment by ypcs** [comment] 2018-06-11 06:48
This is caused by missing wrapper `wp-pull-production-db`. Added in f584c0a, rebuild in progress.

**Comment by ypcs** [comment] 2018-06-11 07:16
@ottok If you'd like to test the fix, `seravo/wordpress-beta` has now the latest image (version 20180605.0.3) with missing wrapper added.

**Comment by ypcs** [comment] 2018-06-11 07:24
This has been released as seravo/wordpress.

**Closed as completed by ypcs** 2018-06-11 07:24 UTC

**Comment by ottok** [comment] 2018-06-11 08:01
Cannot test yet:
```
$ vagrant box update
==> mariadb-box: Checking for updates to 'seravo/wordpress-beta'
    mariadb-box: Latest installed version: 20180605.0.2
    mariadb-box: Version constraints: >= 20160718.15.0122
    mariadb-box: Provider: virtualbox
==> mariadb-box: Box 'seravo/wordpress-beta' (v20180605.0.2) is running the latest version.
```

**Comment by ottok** [comment] 2018-06-11 08:25
I confirm this works now. I did spot the message `==> redacted-box: mysqldump: Can't create/write to file 'pre-production-pull-backup-1528705315.sql' (Errcode: 13)` but I don't know if it matters for now.

In context:
```
==> redacted-box: entering site container... /usr/local/bin/wp-pull-production-db
==> redacted-box: |----------------------------------------------------------------------------|
==> redacted-box: | Welcome to Seravo.com!                                                     |
==> redacted-box: | Unauthorized use is forbidden. All connections are monitored and recorded. |
==> redacted-box: |----------------------------------------------------------------------------|
==> redacted-box: Saving backup of current development database in /data/db/pre-production-pull-backup.sql...
==> redacted-box: mysqldump: Can't create/write to file 'pre-production-pull-backup-1528705315.sql' (Errcode: 13)
==> redacted-box: Define new and old siteurl for later search-replacing...
```
